/** Material Symbols Rounded ligature names (local woff2; FILL=0 / wght=400). */

export const iconNames = {
  home: 'home',
  search: 'search',
  library: 'library_music',
  plugins: 'extension',
  settings: 'settings',
  music: 'queue_music',
  musicNote: 'music_note',
  play: 'play_arrow',
  pause: 'pause',
  previous: 'skip_previous',
  next: 'skip_next',
  volume: 'volume_up',
  volumeMute: 'volume_off',
  shuffle: 'shuffle',
  repeat: 'repeat',
  repeatOne: 'repeat_one',
  list: 'list',
  queueAdd: 'add_to_queue',
  playlistAdd: 'playlist_add',
  minimize: 'minimize',
  maximize: 'crop_free',
  restore: 'open_in_full',
  close: 'close',
  arrowLeft: 'arrow_back',
  arrowRight: 'arrow_forward',
  chevronRight: 'chevron_right',
  chevronDown: 'expand_more',
  check: 'check',
  more: 'more_vert',
  folder: 'folder',
  file: 'description',
  palette: 'palette',
  font: 'format_size',
  moon: 'dark_mode',
  sun: 'light_mode',
  person: 'person',
  login: 'login',
  logout: 'logout',
  refresh: 'refresh',
  sync: 'sync',
  delete: 'delete',
  edit: 'edit',
  add: 'add',
  plus: 'add',
  lyrics: 'lyrics',
  error: 'error',
  info: 'info',
  expand: 'unfold_more',
  download: 'download',
  queue: 'queue_music',
  history: 'history',
  drag: 'drag_indicator',
  skip: 'fast_forward',
};

export function icon(name, extra = '') {
  const ligature = iconNames[name] ?? iconNames.musicNote;
  return `<span class="ui-icon msi ${extra}" aria-hidden="true" focusable="false">${ligature}</span>`;
}
